tap "homebrew/cask"
tap "homebrew/services"
brew "bash-completion"
brew "composer"
brew "dnsmasq", restart_service: true
brew "git"
brew "git-extras"
brew "httpd", restart_service: true
brew "nvm"
brew "php"
brew "python"
brew "python@2"
brew "rbenv"
brew "yarn", args: ["without-node"]
cask "atom"
cask "filezilla"
cask "google-chrome"
cask "firefox"
cask "microsoft-edge"
cask "virtualbox"
